### PR TITLE
fix keyboard issues with notification dialog

### PR DESCRIPTION
**Pull request by flipkick**
fix for #497 

also fixes tab keys for the find dialog.

The "Allow" Button will be the first button selected if you press tab. Maybe you want something different, just change the z order then.

### CODE REVIEW

**Comment by henrypp** [comment]
Hello. Thank you! Do you test it, it's worked?

**Comment by henrypp** [comment]
Yeah, i just check it and saw - it was a bug in messages processsing code and `IsDialogMessage (GetActiveWindow (), &msg)` solve issue, but if SW going to process all actiive windows (not only of app), because GetActiveWinndow returns ALL active windows, so is that?

**Comment by flipkick** [comment]
Hi @henrypp,

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getactivewindow :
```
GetActiveWindow function
Retrieves the window handle to the active window attached to the calling thread's message queue.
```

So, GetActiveWindow is only able to retrieve the active window handle of simplewall, not other apps.

**Comment by flipkick** [comment]
The use of GetActiveWindow() ensures, that only the accelerators and messages of the active simplewall window (the window with the current input focus) are handled. Only problem i can image of, If you use some kind of global hotkeys via main window accelerators, those wouldn't work now, i didn't check for this.

**Comment by flipkick** [comment]
I found a problem, the accelerators of the find dialog won't get handled, instead the main window receives them. As i didn't do any windows desktop programming for a couple of years, i will check how other projects do this and change my pull request.

A more manual message handling would solve the problems, e.g. https://github.com/anaisbetts/libcef/blob/9c15169e3ace68d00f32737efe2a26973be5f1e9/cef1/tests/cefclient/cefclient_win.cpp#L121

**Comment by henrypp** [comment]
> I found a problem, the accelerators of the find dialog won't get handled, instead the main window receives them.

Is the find dialog problem itself, does not matter what is passes into `IsDialogMessage` #511

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/commit/4235474f63ef716ac240b6c49d8521966738994b

**Pull request closed without merging**
