### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Chaython**
Simplewall is no longer less than a mb.
Fixed some grammar, and misspelling of "through".

### CODE REVIEW

**Comment by henrypp** [comment]
> Simplewall is no longer less than a mb.

Why is that?

**Comment by Chaython** [comment]
Compressed it's <700kb, but once unpacked it is <2mb
image
As it's such an insignificant amount, it shouldn't matter, but it's more accurate.

**Comment by henrypp** [comment]
Space reuired for what? Be more specific.

**Comment by Chaython** [comment]
With 3.3.3, it specifies during installation process it requires 1.6mb.
Actual folder size is 
image excluding language pack update + profile data.
If you don't bundle any language file[185KB], make a more simple uninstaller[currently 165kb]  and/or not bundle history file[49KB], you could bring it under 1mb again, excluding profile data. IDK how else you can trim it, nor why it really matters.
I just changed the text from under to only, As you can see.
Through was spelt wrong [t at the end] and some grammar issues, there are some other grammar issues, but in the context perfectly fine.

**Comment by henrypp** [comment]
consider anything do not belong to simplewall is ridiculous, et cetera.

**Comment by Chaython** [comment]
What's not belonging to Simplewall?
A clean install is 1.14MB, excluding the profile which is generated by Simplewall and is miniscule in comparison.
In current revision it's obviously, no longer under 1 MB.
The lang file is bundled and extracted with the installer automatically. So you could achieve <1 MB, simply by adding the option "include additional languages" during install.
 You could make the installer smaller.
Why's it so important to you to be under 1MB, why give yourself such a goal? 
In current default configuration, it's incorrect, it's more than 1MB. I thought this would be a simple merge for you.

**Comment by henrypp** [comment]
>  Why's it so important to you to be under 1MB, why give yourself such a goal?

<s>Why it is important to you?</s>

1) Because the kernel weighs less than megabyte.
2) There is a bug at the installer, the problem with the counting of the section size, installer `[counts both 32 and 64 bit executables](https://github.com/henrypp/builder/blob/3b512acc11ee51f2bfacdbf037ee7824f24f74eb/setup_script.nsi#L116)`, i do not know why, but it is. This is the problem of Nsis, if you know how to solve it, fix it.

>  So you could achieve <1 MB, simply by adding the option "include additional languages" during install.

Wow, really great idea to split kernel and i18n (which may be unused at all).

**Pull request closed without merging**
